project_name: candle
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: main.go
    binary: candle
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - 386
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  prerelease: auto
brews:
  - name: candle
    repository:
      owner: yoshihicode
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/yoshihicode/candle"
    description: "candle is a joke command that displays a candle-like fire effect in your terminal."
    license: "MIT"
    test: |
      system "#{bin}/candle --help"
    install: |
      bin.install "candle"
